# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 13:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20161016_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 16, 13, 19, 18, 228554, tzinfo=utc)),
        ),
    ]
