# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 14:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_auto_20161016_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 16, 14, 22, 10, 180093, tzinfo=utc)),
        ),
    ]
