# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(max_length=100)),
                ('videoId', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('publishedAt', models.DateTimeField()),
                ('thumbnails', models.URLField(blank=True)),
            ],
        ),
    ]
