# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='nickname',
            field=models.CharField(max_length=24, unique=True),
        ),
    ]
